window.QUERY_DIRECTION_CONFIG = [
  {
    id: "why",
    name: "为什么",
    intent: "原因/情绪",
    description: "适合争议、走红、被骂、突然出圈、用户不理解的热点。",
    keywords: ["为什么", "火", "被骂", "争议", "出圈", "不理解", "突然", "情绪"],
    queryTemplates: ["{hotspot}为什么火", "{hotspot}为什么被骂", "{hotspot}为什么争议这么大", "{hotspot}为什么突然出圈", "为什么{subject}{context}"],
  },
  {
    id: "what",
    name: "是什么",
    intent: "概念解释",
    description: "适合新概念、粉丝黑话、体育规则、游戏设定、历史事件。",
    keywords: ["是什么", "什么意思", "概念", "设定", "黑话", "规则", "历史"],
    queryTemplates: ["{subject}是什么", "{subject}是什么意思", "{subject}指的是什么", "{hotspot}里的{context}是什么"],
  },
  {
    id: "mechanism",
    name: "规则/机制",
    intent: "规则机制",
    description: "适合体育赛事、游戏、综艺赛制、投票规则、抽卡机制。",
    keywords: ["规则", "机制", "赛制", "怎么算", "判定", "投票", "抽卡", "奖金"],
    queryTemplates: ["{hotspot}规则", "{hotspot}赛制", "{hotspot}机制", "{hotspot}怎么算", "{hotspot}怎么判定", "{hotspot}奖金怎么分配"],
  },
  {
    id: "background",
    name: "人物背景",
    intent: "人物背景",
    description: "适合明星、运动员、历史人物、综艺嘉宾、游戏角色。",
    keywords: ["背景", "出道", "专业", "早期", "练习生", "个人资料", "考古"],
    queryTemplates: ["{subject}履历", "{subject}怎么出道的", "{subject}是什么专业", "{subject}之前是做什么的", "{subject}早期经历"],
  },
  {
    id: "relationship",
    name: "人物关系",
    intent: "关系/时间线",
    description: "适合 CP、明星关系、游戏人物关系、综艺嘉宾关系。",
    keywords: ["关系", "CP", "合作", "搭档", "认识", "时间线", "结局"],
    queryTemplates: ["{subject}和{secondary}什么关系", "{subject}和{secondary}认识吗", "{subject}和{secondary}合作过吗", "{hotspot}人物关系"],
  },
  {
    id: "trivia",
    name: "冷知识",
    intent: "冷知识",
    description: "适合明星考古、体育赛事、演唱会、游戏/IP、历史向内容。",
    keywords: ["冷知识", "原来", "没想到", "居然", "才发现", "小众", "反差"],
    queryTemplates: ["{subject}冷知识", "{hotspot}冷知识", "{hotspot}有哪些冷知识", "{subject}不为人知的经历"],
  },
  {
    id: "achievement",
    name: "履历/成就",
    intent: "人物成就",
    description: "适合明星、歌手、运动员、综艺嘉宾、历史人物。",
    keywords: ["履历", "成就", "获奖", "代表作", "冠军", "成绩", "水平"],
    queryTemplates: ["{subject}履历", "{subject}获奖记录", "{subject}代表作", "{subject}成就", "{subject}是什么水平"],
  },
  {
    id: "status",
    name: "地位/评价",
    intent: "地位评价",
    description: "适合歌手、演员、运动员、IP作品、综艺节目。",
    keywords: ["地位", "评价", "厉害", "什么水平", "唱功", "演技", "含金量"],
    queryTemplates: ["{subject}什么地位", "{subject}在{field}是什么水平", "{subject}厉害在哪里", "{subject}为什么评价高"],
  },
  {
    id: "controversy",
    name: "争议/纠纷",
    intent: "求证/澄清",
    description: "适合娱乐明星、游戏舆情、粉丝争议、合同纠纷。",
    keywords: ["争议", "纠纷", "被骂", "发生了什么", "雪藏", "合同", "传言", "辟谣", "真的假的"],
    queryTemplates: ["{subject}和{secondary}纠纷", "{hotspot}争议", "{hotspot}为什么被骂", "{hotspot}发生了什么", "{hotspot}真的假的"],
  },
  {
    id: "slang",
    name: "粉丝黑话/梗",
    intent: "圈层梗",
    description: "适合明星粉丝、游戏圈层、KPOP、综艺、互联网梗。",
    keywords: ["粉丝", "叫", "梗", "黑话", "圈层", "KPOP", "昵称", "称呼"],
    queryTemplates: ["为什么{subject}粉丝叫{context}", "{context}是什么意思", "{hotspot}是什么梗", "怎么用{field}方式讲明白{hotspot}"],
  },
  {
    id: "timeline",
    name: "历史/时间线",
    intent: "时间线/经过",
    description: "适合历史游戏、社会事件、娱乐争议、IP剧情、重大赛事。",
    keywords: ["历史", "时间线", "全过程", "前因后果", "正史", "剧情", "结局"],
    queryTemplates: ["{hotspot}时间线", "{hotspot}全过程", "{hotspot}前因后果", "{subject}发生了什么", "{subject}结局"],
  },
  {
    id: "decision",
    name: "实用决策",
    intent: "实用决策",
    description: "适合演唱会、票务、游戏推荐、追星线下、高考志愿、消费种草。",
    keywords: ["值得", "怎么买", "哪里买", "什么时候", "推荐", "位置", "票", "线下"],
    queryTemplates: ["{hotspot}值得去吗", "{hotspot}怎么买", "{hotspot}哪里买", "{hotspot}什么时候", "{hotspot}哪个位置好", "{hotspot}推荐吗"],
  },
  {
    id: "data",
    name: "数据/排行",
    intent: "热度/排行",
    description: "适合身价、票数、涨粉、排名、热度、商业化表现。",
    keywords: ["排行", "排名", "身价", "涨粉", "票数", "奖金", "热度", "人气", "数据"],
    queryTemplates: ["{subject}排行榜", "{subject}人气", "{subject}涨粉", "{subject}排名", "{hotspot}最高奖金多少"],
  },
];

window.HISTORICAL_QUERY_CASES = [
  { hotspot: "2026世界杯", queries: ["世界杯每支队伍奖金多少", "世界杯最高奖金多少", "怎么用KPOP的方式给讲明白世界杯", "世界杯球员身价排行榜"] },
  { hotspot: "盛世天下", queries: ["神龙政变", "武则天和李治结局", "武则天和李治有多少子女", "历史上是王皇后接武媚娘回宫的吗"] },
  { hotspot: "蔡依林北京演唱会", queries: ["蔡依林海外热度", "蔡依林英语专业", "蔡依林蛋糕作品", "蔡依林履历", "蔡依林冷知识"] },
  { hotspot: "宋威龙", queries: ["宋威龙海外人气", "宋威龙长腿老头时期", "宋威龙和于正纠纷", "为什么宋威龙粉丝叫辣条", "宋威龙怎么出道的", "宋威龙冷知识", "宋威龙打游戏厉害吗"] },
  { hotspot: "乘风2026", queries: ["黄灿灿冷知识", "王濛人大硕士", "王濛退役之后都做了什么", "王濛跨行成绩", "唐艺昕第一部戏是什么"] },
  { hotspot: "侯明昊", queries: ["侯明昊男团经历", "侯明昊待播剧", "侯明昊和曾舜曦关系", "侯明昊是哪个男团的"] },
];
